### ISSUE TITLE
[Bug]: Language Switch doesn't work

### ISSUE THREAD

**Issue by michaelrabelo** [vuestorefront/vendure#120]
### Actual Behavior

When trying to switch to the available languages the app reloads but it doesn't change to the chosen language.

### What version of vendure integration are you using?

1.0.0-beta.3

### What version of Node.js are you using?

v14.17.4

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
I think this issue can be related to the fact that currently we do not have a full muli language support. It will be added with #142 . Closing the issue for now.
