### ISSUE TITLE
[Bug]: Order history does not display order content

### ISSUE THREAD

**Issue by michaelbromley** [vuestorefront/vendure#126]
### Expected Behavior

The order history detail view at the `/my-account/order-history` route should display the contents of the order.

### Actual Behavior

An empty table: 
![image](https://user-images.githubusercontent.com/6275952/140064530-d6b39eb5-fec2-4bf9-b872-d5f8e93cd713.png)

### Steps to reproduce

1. Log in
2. Place an order
3. Go to "my account", "order history", "view details"
4. See screen as in screenshot above

### What version of vendure integration are you using?

1.0.0-beta.3

### What version of Node.js are you using?

16.x

### What browser (and version) are you using?

Brave (Chromium 95)

### What operating system (and version) are you using?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
@michaelbromley 

I tried to find the field in the order query that will contain the data about bought products but was not able to find it. Could you provide some guidance here? :)

**Comment by michaelbromley** [comment]
Sure, like this:

```graphql
query {
  order(id: 1) {
    lines {
      id
      unitPriceWithTax
      quantity
      featuredAsset {
        preview
      }
      productVariant {
        id
        name
        sku
      }
    }
  }
}
```
