### ISSUE TITLE
[Bug]: Search input not working

### ISSUE THREAD

**Issue by michaelbromley** [vuestorefront/vendure#127]
### Expected Behavior

When entering a search term in the "search for items" input in the header, and pressing enter, I would expect a search to be performed and the results to be displayed.

### Actual Behavior

Nothing seems to happen - not network request is sent either when I type or when I press "enter".

### Steps to reproduce

Enter a search term into the search bar and press enter.

### What version of vendure integration are you using?

1.0.0-beta.3

### What version of Node.js are you using?

16.x

### What browser (and version) are you using?

Brave (Chromium 95)

### What operating system (and version) are you using?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Search feature is not implemented (it is only mocked for now). It is not a part of the First iteration of the project. I will create an issue to implement search functionality in the next versions (probably 1.1.0), so for now closing this issue.
