### ISSUE TITLE
[Feature]: add Related Products functionality

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/vendure#37]
### How the project can be improved?

Currently we do not have related products functionality but it can be added by modyfying the GraphQL query as in the below example:
![image](https://user-images.githubusercontent.com/37120330/129518291-26740522-419d-4220-a576-a1ceab0493da.png)

Steps to follow:
1. Modify product query
2. Create new getter for the getRelatedProducts functionality
3. Update theme (Product.vue by uncommenting lines about related products)

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zmilan** [comment]
@Baroshem thanks. I like it. I will take it.

**Comment by Baroshem** [comment]
@zmilan 

I would say that you are partly right 😉 Variants of the product are indeed variations of the certain product. However in this example query what was done is that I requested collections (categories) and the productVariants inside these collections. So basically what was done there I requested products that are also part of the same collection that the currently viewed product. It is a variant that is a part of the same collection but not the same product

**Comment by Baroshem** [comment]
Hi @zmilan 

Are you able to finish this task until the end of this week? I would like it to be released with our upcoming 1.0.0-beta.4 version that is planned to land next week.

**Comment by zmilan** [comment]
Hi @Baroshem, I'm sorry for taking so much time. It looks like get more busy than I was planned. If there is someone else that could pick up it, it would be great. Other way I could try to finish it this week (I just can not believe myself too much on this already)

**Comment by Baroshem** [comment]
@zmilan 

No worries, so maybe pick smaller tasks that are planned for the stable 1.0.0 version that is expected to be released until the end of this month?

You can also spend some time playing around with the project template and see if there are any things that need to be fixed before releasing a stable version.

Just look at the project named 1.0.0 😉

**Comment by zmilan** [comment]
@Baroshem thanks, I will check them for sure, and I am not leaving the project. But I think it is not good to keep release waiting on me, since my time is very limited at the moment, and I'm still new to the whole project and how to work with it.
I plan to become more active soon, and especially once when I get more experience with the project and how things works.
