### ISSUE TITLE
Create cart

### ISSUE THREAD

**Issue by rglepper** [vuestorefront/vendure#6]

**Comment by Baroshem** [comment]
I am not sure Vendure has a method to manually create cart. It is a part of VSF methods but I could not found info about it in Vendure so I left it for now. Cart is automatically generated when there is a product added to cart.

**Comment by michaelbromley** [comment]
That's correct, there is no specific mutation to create a new Order, as the Order gets created as needed when adding the first item.

**Comment by Baroshem** [comment]
Closing the issue then
