### ISSUE TITLE
[Feature]: Vendure plugin for Storyblok

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/vendure#94]
### How the project can be improved?

For now we have an integration between Vue Storefront and Storyblok that can be used in integration with Vendure but it would be beneficial to have a plugin for Storyblok that would enable to fetch products from Vendure and display them in Storyblok.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelbromley** [comment]
For reference, here are the docs on adding a FieldType plugin: https://www.storyblok.com/docs/plugins/field-type

**Comment by Baroshem** [comment]
@michaelbromley 

I think this task should not be developed as a part of Vue Storefront as it is mainly related to the backend platform (Vendure) -> plugin will enable to fetch the products directly from Vendure to Storyblok and then it can be used by Vue Storefront integration with Storyblok. But the integration between Vue Storefront and Storyblok is already a thing so the remaining part should be implemented by Vendure contributors.
